### ISSUE TITLE
RPI 4 and RetroPie 4.7.1

### ISSUE THREAD

**Issue by ryu777mtg** [OfficialPhilcomm/retropie-music#1]
Does this work on RPI4 with version 4.7.1 of Retropie?
I have installed fresh install of RetroPie then install this script to no avail during boot up I can see that the background music service fails.
Does the script install all dependencies needed? I noticed at the bottom of the readme here you based much of it off another persons script. Looking at the other script they install a python-pygame package. Does this script need that or does it get installed through this script?
Other than that I'm not sure if it's possible to get to work some help would be nice.

Thanks for your time

**Comment by OfficialPhilcomm** [comment]
You are completely right, the script doesn't install pygame on its own. I will fix that as soon as possible

**Comment by OfficialPhilcomm** [comment]
Can you give me the output of `sudo journalctl -u retropie_background_music`? This should print out any python errors occuring in the script.

**Comment by ryu777mtg** [comment]
Another thing I'd like to ask do i need to edit the rc.local file? Pointing it to the music.py?

Sure I'll try the command but I never got an error during install

**Comment by OfficialPhilcomm** [comment]
One of the big differences to the original script is that this runs as a service in Debian. So you don't need to edit the `rc.local` file.

All dependencies should be installed via the install script, but I might have forgotten something. What is more likely is that there is a python error. Maybe an edge case I didn't cover and thats why the script crashes. If this is the case, `sudo journalctl -u retropie_background_music` should print out the error.

**Comment by ryu777mtg** [comment]
Here it is hope it helps

pi@retropie:~ $ sudo journalctl -u retropie_background_music
-- Logs begin at Thu 2019-02-14 10:12:00 GMT, end at Fri 2020-11-27 13:39:33 GMT
Nov 27 13:39:00 retropie systemd[1]: Started RetroPie Menu Background Music.
Nov 27 13:39:04 retropie python3[385]: /opt/dev_philcomm/music.py:46: RuntimeWar
Nov 27 13:39:04 retropie python3[385]: (ImportError: libSDL2_mixer-2.0.so.0: can
Nov 27 13:39:04 retropie python3[385]:   mixer.init()
Nov 27 13:39:04 retropie python3[385]: pygame 2.0.0 (SDL 2.0.10, python 3.7.3)
Nov 27 13:39:04 retropie python3[385]: Hello from the pygame community. https://
Nov 27 13:39:04 retropie python3[385]: Traceback (most recent call last):
Nov 27 13:39:04 retropie python3[385]:   File "/opt/dev_philcomm/music.py", line
Nov 27 13:39:04 retropie python3[385]:     mixer.init()
Nov 27 13:39:04 retropie python3[385]:   File "/usr/local/lib/python3.7/dist-pac
Nov 27 13:39:04 retropie python3[385]:     raise NotImplementedError(missing_msg
Nov 27 13:39:04 retropie python3[385]: NotImplementedError: mixer module not ava
Nov 27 13:39:04 retropie systemd[1]: retropie_background_music.service: Main pro
Nov 27 13:39:04 retropie systemd[1]: retropie_background_music.service: Failed w
Nov 27 13:39:05 retropie systemd[1]: retropie_background_music.service: Service
Nov 27 13:39:05 retropie systemd[1]: retropie_background_music.service: Schedule
Nov 27 13:39:05 retropie systemd[1]: Stopped RetroPie Menu Background Music.
Nov 27 13:39:05 retropie systemd[1]: Started RetroPie Menu Background Music.
Nov 27 13:39:05 retropie python3[552]: /opt/dev_philcomm/music.py:46: RuntimeWar
Nov 27 13:39:05 retropie python3[552]: (ImportError: libSDL2_mixer-2.0.so.0: can
Nov 27 13:39:05 retropie python3[552]:   mixer.init()
Nov 27 13:39:05 retropie python3[552]: pygame 2.0.0 (SDL 2.0.10, python 3.7.3)
lines 1-23...skipping...
-- Logs begin at Thu 2019-02-14 10:12:00 GMT, end at Fri 2020-11-27 13:39:33 GMT. --
Nov 27 13:39:00 retropie systemd[1]: Started RetroPie Menu Background Music.
Nov 27 13:39:04 retropie python3[385]: /opt/dev_philcomm/music.py:46: RuntimeWarning: use mixer: libSDL2_mixer-2.0.so.0: cannot open shared object file: No such file or directory
Nov 27 13:39:04 retropie python3[385]: (ImportError: libSDL2_mixer-2.0.so.0: cannot open shared object file: No such file or directory)
Nov 27 13:39:04 retropie python3[385]:   mixer.init()
Nov 27 13:39:04 retropie python3[385]: pygame 2.0.0 (SDL 2.0.10, python 3.7.3)
Nov 27 13:39:04 retropie python3[385]: Hello from the pygame community. https://www.pygame.org/contribute.html
Nov 27 13:39:04 retropie python3[385]: Traceback (most recent call last):
Nov 27 13:39:04 retropie python3[385]:   File "/opt/dev_philcomm/music.py", line 46, in <module>
Nov 27 13:39:04 retropie python3[385]:     mixer.init()
Nov 27 13:39:04 retropie python3[385]:   File "/usr/local/lib/python3.7/dist-packages/pygame/__init__.py", line 59, in __getattr__
Nov 27 13:39:04 retropie python3[385]:     raise NotImplementedError(missing_msg)
Nov 27 13:39:04 retropie python3[385]: NotImplementedError: mixer module not available (ImportError: libSDL2_mixer-2.0.so.0: cannot open shared object file: No such file or directory)
Nov 27 13:39:04 retropie systemd[1]: retropie_background_music.service: Main process exited, code=exited, status=1/FAILURE
Nov 27 13:39:04 retropie systemd[1]: retropie_background_music.service: Failed with result 'exit-code'.
Nov 27 13:39:05 retropie systemd[1]: retropie_background_music.service: Service RestartSec=100ms expired, scheduling restart.
Nov 27 13:39:05 retropie systemd[1]: retropie_background_music.service: Scheduled restart job, restart counter is at 1.
Nov 27 13:39:05 retropie systemd[1]: Stopped RetroPie Menu Background Music.
Nov 27 13:39:05 retropie systemd[1]: Started RetroPie Menu Background Music.
Nov 27 13:39:05 retropie python3[552]: /opt/dev_philcomm/music.py:46: RuntimeWarning: use mixer: libSDL2_mixer-2.0.so.0: cannot open shared object file: No such file or directory
Nov 27 13:39:05 retropie python3[552]: (ImportError: libSDL2_mixer-2.0.so.0: cannot open shared object file: No such file or directory)
Nov 27 13:39:05 retropie python3[552]:   mixer.init()
Nov 27 13:39:05 retropie python3[552]: pygame 2.0.0 (SDL 2.0.10, python 3.7.3)
Nov 27 13:39:05 retropie python3[552]: Hello from the pygame community. https://www.pygame.org/contribute.html
Nov 27 13:39:05 retropie python3[552]: Traceback (most recent call last):
Nov 27 13:39:05 retropie python3[552]:   File "/opt/dev_philcomm/music.py", line 46, in <module>
Nov 27 13:39:05 retropie python3[552]:     mixer.init()
Nov 27 13:39:05 retropie python3[552]:   File "/usr/local/lib/python3.7/dist-packages/pygame/__init__.py", line 59, in __getattr__
Nov 27 13:39:05 retropie python3[552]:     raise NotImplementedError(missing_msg)
Nov 27 13:39:05 retropie python3[552]: NotImplementedError: mixer module not available (ImportError: libSDL2_mixer-2.0.so.0: cannot open shared object file: No such file or directory)
Nov 27 13:39:05 retropie systemd[1]: retropie_background_music.service: Main process exited, code=exited, status=1/FAILURE
Nov 27 13:39:05 retropie systemd[1]: retropie_background_music.service: Failed with result 'exit-code'.
Nov 27 13:39:05 retropie systemd[1]: retropie_background_music.service: Service RestartSec=100ms expired, scheduling restart.
Nov 27 13:39:05 retropie systemd[1]: retropie_background_music.service: Scheduled restart job, restart counter is at 2.
Nov 27 13:39:05 retropie systemd[1]: Stopped RetroPie Menu Background Music.
Nov 27 13:39:05 retropie systemd[1]: Started RetroPie Menu Background Music.
Nov 27 13:39:05 retropie python3[598]: /opt/dev_philcomm/music.py:46: RuntimeWarning: use mixer: libSDL2_mixer-2.0.so.0: cannot open shared object file: No such file or directory
Nov 27 13:39:05 retropie python3[598]: (ImportError: libSDL2_mixer-2.0.so.0: cannot open shared object file: No such file or directory)
Nov 27 13:39:05 retropie python3[598]:   mixer.init()
Nov 27 13:39:05 retropie python3[598]: pygame 2.0.0 (SDL 2.0.10, python 3.7.3)
Nov 27 13:39:05 retropie python3[598]: Hello from the pygame community. https://www.pygame.org/contribute.html
Nov 27 13:39:05 retropie python3[598]: Traceback (most recent call last):
Nov 27 13:39:05 retropie python3[598]:   File "/opt/dev_philcomm/music.py", line 46, in <module>
Nov 27 13:39:05 retropie python3[598]:     mixer.init()
Nov 27 13:39:05 retropie python3[598]:   File "/usr/local/lib/python3.7/dist-packages/pygame/__init__.py", line 59, in __getattr__
Nov 27 13:39:05 retropie python3[598]:     raise NotImplementedError(missing_msg)
Nov 27 13:39:05 retropie python3[598]: NotImplementedError: mixer module not available (ImportError: libSDL2_mixer-2.0.so.0: cannot open shared object file: No such file or directory)
Nov 27 13:39:05 retropie systemd[1]: retropie_background_music.service: Main process exited, code=exited, status=1/FAILURE
Nov 27 13:39:05 retropie systemd[1]: retropie_background_music.service: Failed with result 'exit-code'.
Nov 27 13:39:06 retropie systemd[1]: retropie_background_music.service: Service RestartSec=100ms expired, scheduling restart.
Nov 27 13:39:06 retropie systemd[1]: retropie_background_music.service: Scheduled restart job, restart counter is at 3.
Nov 27 13:39:06 retropie systemd[1]: Stopped RetroPie Menu Background Music.
Nov 27 13:39:06 retropie systemd[1]: Started RetroPie Menu Background Music.
Nov 27 13:39:06 retropie python3[599]: /opt/dev_philcomm/music.py:46: RuntimeWarning: use mixer: libSDL2_mixer-2.0.so.0: cannot open shared object file: No such file or directory
Nov 27 13:39:06 retropie python3[599]: (ImportError: libSDL2_mixer-2.0.so.0: cannot open shared object file: No such file or directory)
Nov 27 13:39:06 retropie python3[599]:   mixer.init()
Nov 27 13:39:06 retropie python3[599]: pygame 2.0.0 (SDL 2.0.10, python 3.7.3)
Nov 27 13:39:06 retropie python3[599]: Hello from the pygame community. https://www.pygame.org/contribute.html
Nov 27 13:39:06 retropie python3[599]: Traceback (most recent call last):
Nov 27 13:39:06 retropie python3[599]:   File "/opt/dev_philcomm/music.py", line 46, in <module>
Nov 27 13:39:06 retropie python3[599]:     mixer.init()
Nov 27 13:39:06 retropie python3[599]:   File "/usr/local/lib/python3.7/dist-packages/pygame/__init__.py", line 59, in __getattr__
Nov 27 13:39:06 retropie python3[599]:     raise NotImplementedError(missing_msg)
Nov 27 13:39:06 retropie python3[599]: NotImplementedError: mixer module not available (ImportError: libSDL2_mixer-2.0.so.0: cannot open shared object file: No such file or directory)
Nov 27 13:39:06 retropie systemd[1]: retropie_background_music.service: Main process exited, code=exited, status=1/FAILURE

**Comment by ryu777mtg** [comment]
Whelp figured it out just add this to the install.sh
sudo apt-get install -y libsdl2-mixer-2.0-0

**Comment by OfficialPhilcomm** [comment]
That helped, so what happened is that a new version of pygame exists, which uses `libsdl2` instead of `libsdl`. I updated the script. It should work after uninstall and install the script again.

**Comment by OfficialPhilcomm** [comment]
But like you said, `sudo apt-get install -y libsdl2-mixer-2.0-0` also does the trick.

**Comment by ryu777mtg** [comment]
Just glad it works now though now I can't tell if it still needs a bit of work some of the tunes come in choppy?

Trying different formats mp3 320 and mp3 V0 next is ogg otherwise this is great maybe it needs a bit of overclock but using default on the 8gb model

**Comment by OfficialPhilcomm** [comment]
If the mp3 files seem a bit slowed down, try converting the files to a sample rate of `44100`. I had the same issue, some songs on youtube are in `48000`.

I don't think it is a performance issue, I have it installed on a Pi Zero and it runs good there too

**Comment by ryu777mtg** [comment]
Smelling an enhancement feature to automate conversion 

Ogg works great no choppy slow or reduced quality

**Comment by OfficialPhilcomm** [comment]
The sample rate could be an issue like I said. There are applications like `sox` which can convert the sample rate of a song.

Making a conversion app is a whole other project. I don't think I will implement that as a feature.

But yeah, I am glad everything works for you now, let me know when there are any other issues.

**Comment by ryu777mtg** [comment]
I hear ya thanks for the help marking closed now that its functional as intended
